### PR TITLE
Use socket port for emulator

### PR DESCRIPTION
**Pull request by antonio-fr**
For portability : use port over a Unix file socket.
Works on Windows.

### CODE REVIEW

**Comment by doc-hex** [comment]
This change would break any code using the Unix socket. If you want to do TCP sockets, it should be added without removing the Unix socket support.

**Comment by antonio-fr** [comment]
Which code is using the Unix file socket? I modified the cktap part (cktap transport). Is there any other software that connects to the simulator?

**Comment by antonio-fr** [comment]
You can run the forked code, and see if anything is broken.

**Comment by doc-hex** [comment]
This is an open library. We can never know how the world uses it, so I'd rather not break existing features. I certainly have private code that speaks to this emulator.

**Pull request closed without merging**
